"""New Fields Added In User Model

Revision ID: 0df76665473d
Revises: 4dc5ebc75603
Create Date: 2020-04-14 07:18:26.393327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df76665473d'
down_revision = '4dc5ebc75603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_MASTER_USER', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('MEMORYBLOG_MASTER_USER', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_MASTER_USER', 'last_seen')
    op.drop_column('MEMORYBLOG_MASTER_USER', 'bio')
    # ### end Alembic commands ###
