"""Posts Table

Revision ID: 1da93d9efc24
Revises: ee693e4009d4
Create Date: 2020-06-11 10:05:47.482208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da93d9efc24'
down_revision = 'ee693e4009d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('post_photo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'post_photo')
    # ### end Alembic commands ###
