"""Posts Table

Revision ID: 2e2ee640e21b
Revises: 259fb3608d1a
Create Date: 2020-05-18 21:04:57.735036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2ee640e21b'
down_revision = '259fb3608d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'post_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('post_photo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
