"""Posts Table

Revision ID: 3bdc2cbcb80c
Revises: 754c8c0f9448
Create Date: 2020-05-22 21:26:37.371781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdc2cbcb80c'
down_revision = '754c8c0f9448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('photo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
