"""Users Master Table

Revision ID: 45e3bceff535
Revises: 14209a79c7f5
Create Date: 2020-04-25 14:59:16.429498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e3bceff535'
down_revision = '14209a79c7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_MASTER_USER', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_MASTER_USER', sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
