"""Posts Table

Revision ID: 4dc5ebc75603
Revises: 8368a82edf36
Create Date: 2020-04-11 05:15:25.435363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc5ebc75603'
down_revision = '8368a82edf36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'video')
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('image', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('video', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
