"""Posts Table

Revision ID: 55e608d9af1f
Revises: 2e2ee640e21b
Create Date: 2020-05-22 12:10:31.250866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e608d9af1f'
down_revision = '2e2ee640e21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('photo', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'photo')
    # ### end Alembic commands ###
