"""Posts Table

Revision ID: 754c8c0f9448
Revises: f13164af3af0
Create Date: 2020-05-22 12:23:45.056841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754c8c0f9448'
down_revision = 'f13164af3af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MEMORYBLOG_TRANSACTION_POST', 'photo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MEMORYBLOG_TRANSACTION_POST', 'photo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
