"""PostLike Table

Revision ID: 7ed64a5fafaa
Revises: 1da93d9efc24
Create Date: 2020-06-16 17:10:30.078551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed64a5fafaa'
down_revision = '1da93d9efc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MEMORYBLOG_ASSOCIATION_LIKE_ON_POST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['MEMORYBLOG_TRANSACTION_POST.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['MEMORYBLOG_MASTER_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post_like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['MEMORYBLOG_TRANSACTION_POST.id'], name='post_like_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['MEMORYBLOG_MASTER_USER.id'], name='post_like_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_like_pkey')
    )
    op.drop_table('MEMORYBLOG_ASSOCIATION_LIKE_ON_POST')
    # ### end Alembic commands ###
