"""Users Master Table

Revision ID: 86e8d995bbd4
Revises: 
Create Date: 2020-03-25 07:02:59.169860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e8d995bbd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MEMORYBLOG_MASTER_USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('middlename', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('photo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MEMORYBLOG_MASTER_USER_email'), 'MEMORYBLOG_MASTER_USER', ['email'], unique=True)
    op.create_index(op.f('ix_MEMORYBLOG_MASTER_USER_username'), 'MEMORYBLOG_MASTER_USER', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MEMORYBLOG_MASTER_USER_username'), table_name='MEMORYBLOG_MASTER_USER')
    op.drop_index(op.f('ix_MEMORYBLOG_MASTER_USER_email'), table_name='MEMORYBLOG_MASTER_USER')
    op.drop_table('MEMORYBLOG_MASTER_USER')
    # ### end Alembic commands ###
