"""Private Messages

Revision ID: 99b52232e07e
Revises: 45e3bceff535
Create Date: 2020-04-25 17:23:42.495977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b52232e07e'
down_revision = '45e3bceff535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MEMORYBLOG_TRANSACTION_USER_MESSAGE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('delivered_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['MEMORYBLOG_MASTER_USER.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['MEMORYBLOG_MASTER_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MEMORYBLOG_TRANSACTION_USER_MESSAGE_delivered_time'), 'MEMORYBLOG_TRANSACTION_USER_MESSAGE', ['delivered_time'], unique=False)
    op.add_column('MEMORYBLOG_MASTER_USER', sa.Column('last_message_seen_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_MASTER_USER', 'last_message_seen_time')
    op.drop_index(op.f('ix_MEMORYBLOG_TRANSACTION_USER_MESSAGE_delivered_time'), table_name='MEMORYBLOG_TRANSACTION_USER_MESSAGE')
    op.drop_table('MEMORYBLOG_TRANSACTION_USER_MESSAGE')
    # ### end Alembic commands ###
