"""Users Master Table

Revision ID: b28ed9f28097
Revises: ed61e3c7e634
Create Date: 2020-06-29 08:00:02.894357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28ed9f28097'
down_revision = 'ed61e3c7e634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_MASTER_USER', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_MASTER_USER', sa.Column('photo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
