"""Posts Likes Table

Revision ID: bf5930ceac4e
Revises: 3bdc2cbcb80c
Create Date: 2020-05-23 12:48:51.970951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5930ceac4e'
down_revision = '3bdc2cbcb80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['MEMORYBLOG_TRANSACTION_POST.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['MEMORYBLOG_MASTER_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like')
    # ### end Alembic commands ###
