"""Posts Table

Revision ID: dd881b2777a8
Revises: b28ed9f28097
Create Date: 2020-06-29 08:07:31.486748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd881b2777a8'
down_revision = 'b28ed9f28097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'post_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('post_photo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
