"""Comments Table

Revision ID: ed61e3c7e634
Revises: 7ed64a5fafaa
Create Date: 2020-06-16 17:23:56.059511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed61e3c7e634'
down_revision = '7ed64a5fafaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MEMORYBLOG_ASSOCIATION_COMMENT_ON_POST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['MEMORYBLOG_TRANSACTION_POST.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['MEMORYBLOG_MASTER_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MEMORYBLOG_ASSOCIATION_COMMENT_ON_POST_timestamp'), 'MEMORYBLOG_ASSOCIATION_COMMENT_ON_POST', ['timestamp'], unique=False)
    op.drop_index('ix_comments_timestamp', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['MEMORYBLOG_TRANSACTION_POST.id'], name='comments_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['MEMORYBLOG_MASTER_USER.id'], name='comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.create_index('ix_comments_timestamp', 'comments', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_MEMORYBLOG_ASSOCIATION_COMMENT_ON_POST_timestamp'), table_name='MEMORYBLOG_ASSOCIATION_COMMENT_ON_POST')
    op.drop_table('MEMORYBLOG_ASSOCIATION_COMMENT_ON_POST')
    # ### end Alembic commands ###
