"""Posts Table

Revision ID: f13164af3af0
Revises: 55e608d9af1f
Create Date: 2020-05-22 12:18:42.574377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13164af3af0'
down_revision = '55e608d9af1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEMORYBLOG_TRANSACTION_POST', sa.Column('photo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEMORYBLOG_TRANSACTION_POST', 'photo')
    # ### end Alembic commands ###
